# Introducción General {#cap:ig}

## Problema de investigación

  El crecimiento desmedido de la población y la ambición de la sociedad por mejorar su calidad de vida, han resultado en un creciente deterioro ambiental. La atmósfera no es ajena a este deterioro que acaba empeorando la calidad del aire, impactando de forma directa en la calidad de vida de las personas. Se considera contaminante atmosférico a cualquier sustancia emitida al aire desde una fuente biogénica, geogénica o antropogénica, que es ajena a la composición natural del aire, o que se presenta en concentraciones superiores a las naturales, y que puede poner en riesgo a los seres vivos en un corto o largo plazo [@seinfeld1998air; @fuzzi2015particulate].
  
  Uno de los contaminantes más preocupantes en atmósferas urbanas son los aerosoles atmosféricos, suspensiones relativamente estables de partículas sólidas o líquidas en un gas y que presentan un diámetro menor a 10 $\mu m$. Distinto es a lo que refiere el término material particulado (PM), el cual define un conjunto de materia en estado sólido y/o líquido presente en suspensión en la atmósfera, excluyendo el agua pura [@meszaros1999fundamentals; @salameh2015pm2]. Los aerosoles engloban tanto las partículas en suspensión como la masa de aire en la que se encuentran [@finlayson1999chemistry; @vandenboer2013understanding]. A pesar de su diferencia semántica que demuestra que no son equivalentes, estos términos son utilizados indistintamente.

  Los cambios en la calidad del aire no siempre están ligados a la intervención del ser humano, las fuentes de emisión de partículas pueden clasificarse en antropogénicas y naturales. Se entiende por fuentes antropogénicas aquellas originadas como resultado de la actividad humana, este grupo aglomera procesos industriales, mecánicos y de combustión, construcción y demolición, agricultura y ganadería, entre otros. Por otra parte, las emisiones naturales refieren a partículas generadas como consecuencia de procesos naturales como las erupciones volcánicas, incendios originados a partir de rayos, re suspensión de partículas por el viento, entre otras [@pey2008caracterizacion; @jimenez2008use].
  
  Las propiedades aerodinámicas engloban las características físicas de mayor relevancia para el PM. Estas no solo determinan el tipo de transporte y remoción en la atmósfera, si no que también su deposición en el sistema respiratorio, además de permitir identificar la fuente que les dio origen. El diámetro aerodinámico es la propiedad de mayor relevancia, este refiere al diámetro de una esfera de densidad unitaria (1 $\frac{kg}{cm^3}$) con las mismas características aerodinámicas que la partícula bajo consideración. Según este pueden clasificarse en tres grandes grupos: gruesas (PM~10~: 2.5-10 $\mu m$), finas (PM~2.5~: menor a 2.5 $\mu m$) y ultrafinas (PM~0.1~: menor a 0.1 $\mu m$) [@kulkarni2011aerosol; @gopalakrishnan2015bipolar].

  De acuerdo a su mecanismo de formación, los aerosoles atmosféricos pueden clasificarse en partículas primarias y secundarias. Las partículas primarias son aquellas emitidas de forma directa a la atmósfera y que permanecen en ella de la misma forma en que fueron liberadas. Por otra parte, las partículas secundarias son aquellas que han estado sujetas a cambios químicos o bien son producto de reacciones entre dos o más contaminantes primarios en la atmósfera [@finlayson1999chemistry; @vandenboer2013understanding].

  De acuerdo con los informes de la Organización Mundial de la Salud (OMS), el PM es considerado uno de los contaminantes atmosféricos más perjudiciales para la salud de las personas [@who2005whoro]. Su presencia en la atmósfera impacta significativamente en el desarrollo de la sociedad dado que afecta múltiples componentes con los cuales el ser humano interactúa, además de su salud, se destaca el efecto que tiene en los ecosistemas y en clima.

  La vía de ingreso de las partículas al cuerpo humano es a través del sistema respiratorio y su impacto en la salud depende de múltiples factores tales como el tamaño, componentes adsorbidos, composición química, condición sanitaria del individuo expuesto, intensidad y duración de la exposición. A medida que el tamaño disminuye su peligrosidad aumenta dada su capacidad de penetrar más profundamente en el sistema respiratorio y su mayor facilidad para ser respiradas. Las partículas gruesas se depositan en la tráquea, bronquios y bronquiolos, mientras que las finas y ultrafinas son capaces de alcanzar los alvéolos pulmonares, donde pueden disolverse o depositarse [@kim2015review; @schlesinger2007health]. Además, su capacidad de generar efectos adversos a la salud también se encuentra ligado a los componentes adsorbidos que transporta, entre los más nocivos se destacan metales y microorganismos patógenos [@nordberg2014handbook; @blanco2006caracterizacion]. Por otra parte, se destaca su composición química, la cual determina el carácter cancerígeno y mutagénico de la partícula, los mayores referentes en cuanto a su capacidad de generar adversidades a la salud son los hidrocarburos aromáticos policíclicos [@smoke2004iarc; @iarc2010some]. Finalmente, los efectos varían con la intensidad y duración de la exposición a la que se ven sometidos los individuos, además de su condición sanitaria y edad. La parte de la población más susceptible de sufrir efectos adversos a la salud incluye a niños, embarazadas, personas mayores de 65 años y personas con enfermedades cardiovasculares y/o respiratorias [@sacks2011particulate; @zhao2020fine].

  El impacto en los ecosistemas deriva de la deposición de los aerosoles en la superficie de las plantas, generando abrasión y calentamiento radiativo, conduciendo a una reducción de la capacidad fotosintética. Además, si los compuestos depositados son ácidos o alcalinos, pueden causar lesiones en la superficie de la hoja [@rai2014leaf; @rai2016impacts]. Por otra parte, el PM depositado de forma directa en el suelo puede intervenir en el ciclado de nutrientes en los ecosistemas, afectando principalmente el ciclo del nitrógeno, dado su efecto en las bacterias y hongos de la rizosfera. Adicionalmente, los animales resultan afectados de una forma equivalente a la que es afectada la población humana, variando el impacto en función de la sensibilidad de cada especie.
  
  La influencia de los aerosoles atmosféricos en el clima, deriva de su incidencia en el equilibrio térmico de la tierra y el cambio climático global, la cual se halla vinculado a múltiples procesos. En primer lugar, resalta su influencia en el balance radiativo de la tierra, como consecuencia de la absorción y dispersión de la radiación solar incidente. En segundo lugar, destaca su participación en la formación de nubes y precipitaciones, derivada de su capacidad de actuar como núcleos de condensación. Además, esta influencia en la radiación se encuentra ligada a sus propiedades fisicoquímicas, dando lugar a efectos de enfriamiento y calentamiento de la atmósfera terrestre. Las partículas compuestas por sulfatos se caracterizan por generar un enfriamiento de la atmósfera, mientras que aquellas con una proporción notable de carbono en estado elemental y partículas de polvo tienen un efecto de calentamiento [@chen2021possible]. Por otra parte, el proceso por medio del cual la formación de nubes desencadena una influencia en el balance radiativo de la tierra tiene origen en un aumento en el número de partículas, que desencadena un incremento del espesor óptico de las nubes, disminuyendo la radiación solar superficial neta incidente. Cabe destacar que partículas más pequeñas disminuyen la eficiencia del proceso de precipitación, prolongando de este modo la vida media de las nubes [@unkavsevic2003effects]. Además, aerosoles atmosféricos antropogénicos como el hollín actúan afectando el contenido de agua de las nubes causando un forzamiento radiativo negativo [@solomon2007climate]. Por otro lado, dada la naturaleza de los aerosoles y su participación en un gran número de reacciones secundarias, afectan la concentración y distribución de gases traza atmosféricos, alterando los ciclos de nitrógeno, azufre y oxidantes atmosféricos [@meszaros1999fundamentals; @salameh2015pm2].
  
  El monitoreo de la calidad del aire es una herramienta fundamental a la hora de identificar y evaluar problemas de contaminación [@organizacion2021global]. No obstante, es preocupante que no exista una equitativa accesibilidad a sistemas de monitoreo certificados a lo largo de los distintos países del mundo. Esto ha generado una notoria brecha en el acceso a datos de calidad del aire entre países desarrollados y en vías de desarrollo. Esta tesis centra su objetivo en el desarrollo de un sistema de alerta ante condiciones adversas de calidad de aire de bajo costo, de esta forma abordando la inaccesibilidad a sistemas de monitoreo de referencia en países subdesarrollados. Esta innovadora solución basada en tecnologías económicas, tiene como objetivo permitir a las ciudades de países en vías de desarrollo gestionar y controlar su calidad del aire, salvaguardando así la salud pública. 
  
  En primer lugar, la creación de este sistema, requiere recopilar datos sobre contaminantes atmosféricos, este estudio se centro en el control de la concentración de PM~2.5~, pero podría ser aplicable a cualquier contaminante en cuestión. Por este motivo, fue necesario desarrollar un sistema de monitoreo basado en sensores de bajo costo que permitiese disponer de registros del contaminante a lo largo del tiempo. Una vez obtenidos estos datos, dada a la estrecha relación de vinculación existente entre la concentración de PM~2.5~ y las variables satelitales meteorológicas [@tiwari2017assessment; @he2017influences], es que se recurrió a éstas para definir el estado de la atmósfera en un momento determinado con el objetivo de captar su covariabilidad. En consecuencia, se procedió a descargar múltiples variables satélites de fácil acceso y de dominio público (bajo costo). La incorporación de estas variables como predictoras en nuestro sistema de alerta permitirá explicar las fluctuaciones en la concentración de PM~2.5~, siguiendo la premisa de un sistema económico. 
  
  Finalmente, se buscó captar esta interrelación por medio de la implementación de algoritmos de inteligencia artificial. Estos algoritmos permiten obtener predicciones futuras de la variable respuesta con un horizonte de predicción, en nuestro caso con cinco días de anticipación. La elección del horizonte de predicción se encuentra fundada en que la disponibilidad de las variables satelitales es gratuita solo cinco días antes respecto del momento presente, de esta forma para poder obtener la predicción de la hora siguiente, es necesario emplear como predictoras los datos de la hora anterior con cinco días de antelación. Los algoritmos de inteligencia artificial entrenados captaran la variabilidad de la concentración de PM~2.5~ respecto de las variables satelitales con cinco días de antelación, a pesar de esto como consecuencia de su disponibilidad, solo permitirá la predicción de la concentración de PM~2.5~ la hora siguiente. Por otra parte, si los datos de variables satelitales se obtuviesen en tiempo real, se permitiría obtener predicciones con cinco días de anticipación. Además, podría entrenarse otro algoritmo considerando cualquier ventana de tiempo en función del objetivo deseado. La implementación de estos algoritmos permitirá capturar y explicar la variabilidad del contaminante en cuestión, prescindiendo así de los sistemas de medición en tierra y posibilitando la realización de predicciones futuras de la concentración de PM~2.5~. De esta forma, se pretende lograr el desarrollo de un sistema de alerta de bajo costo ante condiciones adversas de calidad del aire, cuya potencialidad deviene de la capacidad de alertar a la población y proteger la salud pública.
  
## Motivación

  Estudios previamente realizados en la ciudad de Córdoba han demostrado que se convive con elevadas concentraciones de PM, especialmente en la zona céntrica, cuya principal fuente de emisión se vincula al transporte [@carreras2001comparison; @carreras2006situ; @amarillo2021exploratory]. También se ha demostrado la asociación entre los niveles de PM y los riesgos de enfermedades respiratorias en la población de la ciudad de Córdoba [@carreras2009assessment; @mateos2018land; @busso2021modeling]. Además, la relación existente entre los niveles de PM y variables meteorológicas satelitales para el sitio de interés también ha sido foco de investigación [@amarillo2021exploratory; @della2018analisis]. Sin embargo, ninguno de estos estudios ha analizado la variable respuesta con una frecuencia de variación horaria, ni siguiendo un enfoque de series temporales que permita analizar la variabilidad conjunta de la concentración horaria de PM respecto de otras covariables. 

  Actualmente existe abundante información respecto de: los efectos nocivos del PM en la salud del hombre, su composición, fuentes de emisión, relación con otras covariables y su modelado predictivo. A pesar de esto, la mayoría de los estudios se han realizado en países de Europa y América del Norte. En los últimos años ha ocurrido una creciente contribución a esta área en el resto del mundo, permitiendo comparar diferentes situaciones en cuanto a niveles y tipos de emisión, así como respecto de las condiciones socioeconómicas de la población. Dado que las condiciones meteorológicas, topográficas y las actividades antropogénicas en un sitio específico determinan los patrones de emisión de PM, se ve justificada la realización de estudios de monitoreo in situ. Hasta el día de hoy, en la ciudad de Córdoba, se han desarrollado estudios que demuestran los impactos en la salud de este contaminante, además de su relación con covariables y la identificación de su fuente de emisión dada su composición [@amarillo2021exploratory; @mateos2019influence; @mateos2018land; @busso2021modeling]. Sin embargo, ningún estudio realizado en el país ha tenido por objetivo el desarrollo de un modelo predictivo de contaminación de aire en pos de generar un sistema de alerta temprana ante condiciones adversas de calidad de aire implementando técnicas de inteligencia artificial para la concentración horaria de PM~2.5~.

  Contar con información sobre la variabilidad del PM y su relación con variables satelitales en diversas escalas temporales en distintos sitios del área metropolitana de la provincia de Córdoba, permitirá caracterizar tanto espacial como temporalmente este contaminante. Además, estos resultados son el punto de partida para el desarrollo de modelos estadísticos de elevada capacidad predictiva, ya que no solo aprovechan la variabilidad respecto de covariables satelitales, si no que también la respecto de información espacial y temporal derivada del análisis exploratorio. Esto permitirá la creación de un sistema de alerta cuya capacidad predictiva se vea potenciada, así permitiendo advertir ante condiciones adversas de calidad de aire, reforzando así los pilares en los que se sustenta la salud pública, garantizando una mejor calidad de vida a la población. Finalmente, la disponibilidad de nuevos datos paleará la falta de acceso a información de contaminación de aire en la provincia. 
  
  La inaccesibilidad a sistemas de monitoreo de referencia en países cuyos ingresos son limitados genera una ausencia de control y gestión de la calidad del aire. La capacidad de generar redes de vigilancia de la calidad del aire basadas en equipos certificados de referencia es exclusivo de países desarrollados económicamente dados sus elevados costes de adquisición y mantenimiento. Esto es prohibitivo para países subdesarrollados que dejan la gestión y control de calidad de aire de lado al ser una necesidad secundaria. Por este motivo, el presente trabajo busca desarrollar un sistema que permita la alerta temprana ante condiciones adversas de calidad del aire inmerso en un contexto de bajo costo, paleando la inaccesibilidad a este pilar fundamental de la salud pública en dichos paises.
  
## Desafíos metodológicos

  Los procesos de contaminación atmosférica varían de manera continua en el tiempo y en el espacio. Por este motivo, resulta de interés predecir la concentración de contaminantes atmosféricos referenciados a un determinado momento de tiempo y ubicación geográfica. Los datos que alimentan estos análisis son series temporales condicionadas a una locación espacial, o bien una colección de observaciones recogidas secuencialmente en el tiempo georreferenciadas a un sitio en particular. Cabe destacar que la variabilidad espacio temporal de los contaminantes no se encuentra determinada solo por las características espaciales y temporales de los datos recopilados, sino por múltiples covariables que también varían espacial y temporalmente, en este caso las variables satelitales.

  En parte, la novedad de la investigación recae en el análisis de series temporales de PM~2.5~ cuya frecuencia de observación es horaria, es decir, que los datos se encuentran equiespaciados por un intervalo de tiempo igual a una hora, algo nunca antes realizado para la provincia de Córdoba, Argentina. El primer impedimento a esta investigación es la ausencia de un sistema de medición y seguimiento de este tipo de contaminante en la escala temporal de interés. Como consecuencia, para poder recopilar los datos, fue necesario el desarrollo de sensores que permitiesen monitorear y recopilar datos de concentración de PM~2.5~ en la frecuencia temporal de interés. Estos debieron ser diseñados y ensamblados desde cero, atravesando todas las etapas transversales en el desarrollo de un equipo de monitoreo, desde la creación del algoritmo y el software, hasta el ensamblado de los prototipos finales y su validación con respecto a un sistema de referencia certificado. 

  Una vez obtenidos los datos del contaminante de interés debió procederse con una exhaustiva limpieza y pre tratamiento de los datos, de acuerdo a las características espaciales y temporales particulares de cada uno. Por este motivo fue inevitable un análisis condicionado tanto por ubicación geografía como por momento de tiempo, garantizando una limpieza exclusiva para cada uno de los sitios y periodos de tiempo considerados. Como consecuencia se volvió necesario el estudio de la variabilidad explicada por cada una de las variables temporales derivadas, con el objetivo de determinar el porcentaje de variabilidad representado por cada una de ellas. 

  El estudio de series temporales tiene como característica principal la dependencia que vincula observaciones contiguas, además esta dependencia puede verse influenciada por comportamientos estacionales. Es importante determinar cuáles son los factores temporales que desencadenan la estacionalidad que influencia la serie temporal, para así contar con las herramientas necesarias para explicar su variabilidad. Además, las características propias de las series temporales son las que nos permitirán encontrar relaciones entre las distintas ubicaciones espaciales donde los datos fueron recopilados. Por otra parte, determinar estas características de la serie temporal es necesario para poder entrenar un algoritmo predictivo que logre acertadas predicciones de la concentración de PM~2.5~.

  Como se mencionó anteriormente, no basta solo con variables derivadas de las características espaciales y temporales para explicar la variabilidad del contaminante en cuestión. Por este motivo, el análisis debió complementarse con covariables que permitiesen describir la forma en que varían los datos espacio temporalmente. De esta forma, fue necesaria la inclusión de otras variables que fluctuasen conjuntamente con la concentración de PM~2.5~ durante el período de muestreo, en la misma frecuencia de temporal y ubicación geográfica en que los datos fueron recopilados por los sensores desarrollados. De esta forma se vuelve imprescindible el estudio de diversas fuentes de datos satelitales para poder llevar a cabo su descarga y análisis conjunto. 

  El modelado estadístico busca captar la forma en que se desencadena la variabilidad conjunta de la variable respuesta (concentración de PM~2.5~) con respecto a las ingresadas como predictoras, en función de los datos de entrenamiento, con el objetivo de lograr generar predicciones en datos donde no se cuenta con la respuesta. El análisis de variabilidad conjunto de la respuesta en función de las covariables y la incorporación de mecanismos de selección de características permitirá identificar un subconjunto de datos que maximice la explicación de la forma en que fluctúa la concentración de PM~2.5~, resultando en una reducción de la dimensionalidad y disminuyendo la complejidad. Además, este análisis se complementa con la creación de nuevas características derivadas de los datos existentes, algo que permitirá la introducción de covariables que garanticen una mejor representación de la variable respuesta. Finalmente, es fundamental el estudio de múltiples algoritmos y modelos estadísticos, con el objetivo de determinar cuál de ellos es el que mejor ajusta a los datos, logrando captar la variabilidad presente y garantizando predicciones de elevada exactitud.

  El objeto de este trabajo es proveer las herramientas necesarias para la creación de un sistema de alerta ante condiciones adversas de calidad de aire de bajo costo. En primer lugar es necesaria la creación de un sistema de monitoreo económico y su validación con respecto a una estación de referencia. Posteriormente es necesario recopilar datos de concentración de PM~2.5~, ademas de buscar covariables que permitan explicar su variabilidad. Una vez obtenidos los datos, es necesario llevar a cabo el modelado predictivo, modelado que busca inferir la forma en que se vinculan las covariables y la concentración de PM~2.5~, con el objetivo de explicar sus fluctuaciones y obtener predicciones acertadas. La principal aplicación de estos modelos recae en alertar a la población ante condiciones adversas de calidad de aire en ciudades de países días vías de desarrollo con un horizonte de predicción de cinco días, permitiendo la accesibilidad a datos de calidad de aire y preservando la salud pública.

### Objetivo general

  Desarrollar un modelo predictivo de concentración de aerosoles para el área metropolitana de la provincia de Córdoba en función de variables: satelitales de acceso público, meteorológicas, temporales y de uso de suelo, y validar el empleo de sensores de bajo costo para determinar partículas finas en áreas urbanas. 

### Objetivos específicos

  1. Describir la variación espacio temporal de la concentración de aerosoles colectados en zonas del Área Metropolitana de Córdoba, Argentina.
 
  2. Evaluar la utilidad de sensores de bajo costo para el estudio de aerosoles en zonas urbanas del Área Metropolitana de Córdoba, Argentina. 
  
  3. Analizar la influencia de variables satelitales en los patrones de variación temporal de aerosoles en el Área Metropolitana de Córdoba, Argentina. 
  
  4. Estimar la contribución relativa de productos satelitales para predecir la concentración de material particulado en el Área Metropolitana de Córdoba, Argentina. 
  
  5. Estimar un modelo predictivo que incluya variables de uso de suelo, satelitales y temporales relacionadas a la variación periódica para la estimación de la concentración de aerosoles en el Área Metropolitana de Córdoba, Argentina.
  