# Comentarios finales {-}

  Este apartado sintetiza los aspectos más relevantes de la tesis, destacando los procedimientos realizados, los resultados obtenidos y las discusiones que han proporcionado información novedosa. Su objetivo principal esta orientado a dar respuesta a los objetivos específicos planteados al principio de esta tesis, así como al objetivo general, que busca desarrollar un modelo predictivo de concentración de aerosoles para el Área Metropolitana de Córdoba utilizando datos de sensores de bajo costo, variables derivadas de información satelital de acceso público, variables meteorológicas, temporales y de uso del suelo, y validar el empleo de estos sensores en áreas urbanas.
  
  El proceso de ensamblaje y calibración de los sistemas de monitoreo de bajo costo, descrito en detalle en el capítulo [2](#cap:sens), fue crucial para asegurar la integración efectiva y funcional de los sensores. Este meticuloso proceso incluyó la conexión de sensores a la placa Arduino mediante cables pelados y soldados con mercurio líquido, garantizando uniones firmes y conductoras al solidificarse. La carga del *firmware* se realizó directamente desde una computadora, estableciendo una configuración robusta y fiable del sistema de monitoreo. Los sistemas de bajo costo mostraron una alta consistencia en las mediciones de PM~2.5~, comparables con los datos de la estación de referencia de la ciudad, sugiriendo que estos sistemas pueden ser empleados eficazmente para monitorear la calidad del aire en zonas urbanas. 
  
  La variación espacio-temporal de la concentración de aerosoles en el área metropolitana de Córdoba, explorada en el capítulo [3](#cap:expl), reveló que, aunque las concentraciones de PM~2.5~ en Córdoba son menores que en otras ciudades del mundo, los estándares de calidad del aire locales fueron superados en múltiples ocasiones. La magnitud de la concentración promedio anual de PM~2.5~ encontrada para la provincia de Córdoba (30/03/2021-30/03/2022) fue inferior a la observada en otras ciudades del mundo. Por ejemplo, en Riohacha, Colombia (188.014 habitantes), se registró una concentración de 14.57 $\frac{\mu g}{m^3}$ (04/11/2010-02/02/2011) [@rojano2013niveles]. En Brasil, ciudades como Río de Janeiro (15.5 $\frac{\mu g}{m^3}$) (6.320.446 habitantes) (01/06/2007-01/08/2008) y Porto Alegre (13.9 $\frac{\mu g}{m^3}$) (1.420.667 habitantes) (01/10/2001-01/12/2002) también presentaron niveles superiores a los observados en la provincia de Córdoba [@de2012urban]. En Serbia, se reportaron concentraciones de promedios anuales de entre 13.93 $\frac{\mu g}{m^3}$ y 28.91 $\frac{\mu g}{m^3}$ para el periodo comprendido entre los años 2001 y 2016 [@stanojevic2019spatio] (6.834.000 habitantes). Por último, en Estambul, Turquía, se registraron concentraciones de promedios anuales de entre 47.8 $\frac{\mu g}{m^3}$ y 93.0 $\frac{\mu g}{m^3}$ para el periodo comprendido entre 2007 y 2008, en distintas regiones de la ciudad [@rasheed2015measurement] (15.019.000 habitantes). Sin embargo, los estándares de calidad de aire establecidos por las normativas de la OMS y la EPA fueron superados en múltiples ocasiones tanto en la escala anual como de promedio de 24 horas. Al segmentar los datos en función del uso del suelo característico del patrón de emisión en cada sitio de muestreo, se observó una marcada correspondencia entre la frecuencia de superación de estos límites y las particularidades de cada uno de los clústeres identificados (agricultura/área verde, urbano e industrial). 
  
  El análisis de las series temporales de PM~2.5~ mostró patrones de emisión característicos de cada uso del suelo, con concentraciones más altas en zonas industriales en comparación con áreas urbanas y agrícolas/áreas verdes. La distribución *gamma* se ajustó mejor a los datos de concentración de PM~2.5~, minimizando los valores del criterio de información de Akaike (*AIC*) y del criterio de información Bayesiano (*BIC*), y proporcionando un modelo teórico que explicó adecuadamente la variabilidad observada. Tanto las características temporales como espaciales de estas series demostraron potencial para explicar la variabilidad de los niveles de PM~2.5~, convirtiéndolas en una valiosa entrada para la construcción de modelos predictivos. Además, se observaron diferencias notables en las características de las series de tiempo de concentración de PM~2.5~ en función del uso del suelo, resaltando la importancia de considerar estas variaciones al analizar y abordar la calidad del aire.

  Por otra parte, el análisis exploratorio resaltó el potencial que podrían tener las variables estudiadas para explicar la variabilidad de la concentración de PM~2.5~. En busca de cumplir con el objetivo de ajustar modelos predictivos, se recopilaron numerosas variables que pudieran reflejar las características de la atmósfera en un momento determinado. La base de datos final incorporó un total de 193 variables, a partir de la cual se exploraron distintas técnicas de modelado predictivo. Cabe destacar que el enfoque de modelado predictivo se encontró enmarcado en uno meramente computacional, diferenciándose de uno mecanicista. La diferencia principal radica en que, en este caso, el objetivo principal es obtener un modelo con una alta capacidad predictiva, a diferencia del enfoque mecanicista que busca inferir las relaciones subyacentes entre las variables involucradas. Es importante reconocer que los modelos deterministas también tienen una alta capacidad predictiva y han mostrado buenos resultados en diversos estudios. Por ejemplo, el *Regional Air Quality Deterministic Prediction System (RAQDPS)* desarrollado por *Environment Canada* ha demostrado eficacia en la predicción de concentraciones de PM~2.5~ en diferentes regiones. Este sistema integra la meteorología y la química atmosférica para proporcionar predicciones precisas de la concentración de partículas hasta 72 horas antes, permitiendo alertar a la población ante condiciones adversas de calidad de aire y detectar incendios forestales de manera temprana. Además, existen numerosos estudios que han implementado modelos predictivos utilizando diferentes enfoques y técnicas para la predicción horaria de la concentración de PM~2.5~. Chen et al., (2023) desarrollaron un modelo híbrido *CNN-RF* (*Convolutional Neural Network - Random Forest*) que mostró un rendimiento robusto en la predicción de la concentración de PM~2.5~, logrando un *RMSE* de 3.67 $\frac{\mu g}{m^3}$ para la hora siguiente [@chen2023pm2]. Por otra parte, Zhong et al., (2021) comparó un modelo de red neuronal profunda con el *Community Multiscale Air Quality (CMAQ)* y encontró que el modelo de red neuronal proporcionaba mejores predicciones horarias de PM~2.5~ con un RMSE de 19.19 $\frac{\mu g}{m^3}$ para la hora siguiente en Beijin [@zhong2021robust]. Estos estudios subrayan la capacidad de los modelos de aprendizaje profundo para captar la complejidad de los datos derivados de información satelital y ofrecer predicciones precisas a partir de una estrategia de modelado mecanicista 

  Las variables derivadas a partir de información satelital demostraron potencial para explicar la variabilidad espacio temporal de la concentración de PM~2.5~, como se detalla en el capítulo [4](#cap:var). Estas variables, que forman un sistema dinámico e interdependiente, no actúan de manera aislada sino que su dinámica conjunta determina los patrones de dispersión de contaminantes atmosféricos. El análisis exploratorio de la covariación entre estas variables y la concentración de PM~2.5~ justificó su inclusión en la base de datos para el desarrollo de modelos predictivos, resaltando su potencial para explicar la variabilidad espacio-temporal de la concentración de aerosoles en el área de estudio. Su inclusión en el modelado predictivo asegura la captura de la variabilidad de la variable objetivo y la obtención de estimaciones precisas. La similitud existente entre las métricas obtenidas para el modelo de referencia y las de los modelos predictivos desarrollados indican que estos poseen potencial para cumplir el objetivo de alertar a la población ante condiciones adversas de calidad de aire con cinco días de anticipación. 

  Los resultados obtenidos en el capítulo [5](#cap:var) indican que los modelos predictivos desarrollados demuestran potencial para alertar a la población ante condiciones adversas de calidad de aire con cinco días de anticipación. Estos modelos demostraron ser capaces de interpretar adecuadamente las relaciones subyacentes entre la concentración de PM~2.5~ y las variables derivadas de información satelital. La similitud entre las métricas obtenidas para el modelo de referencia y las de los modelos predictivos desarrollados sugiere que estos poseen el potencial para cumplir con el objetivo de alerta temprana. Además, se observó que las características propias de la variabilidad de cada una de las series temporales en los diferentes usos de suelo, junto con las características de aprendizaje de cada uno de los modelos predictivos ajustados, influyeron significativamente en el rendimiento de los algoritmos. Para el uso del suelo agrícola y área verde (menor variabilidad) el algoritmo de bosques aleatorios demostró mayor capacidad predictiva. Mientras que en el uso del suelo urbano e industrial (mayor variabilidad) los de aprendizaje profundo permitieron ajustar modelos de mayor capacidad predictiva. 

## Repuesta a los objetivos

### Objetivo general

  El objetivo general de esta tesis fue desarrollar un modelo predictivo de concentración de aerosoles para el área metropolitana de la provincia de Córdoba a partir de datos relevados por sensores de bajo costo, en función de variables derivadas a partir de información satelital de acceso público, variables meteorológicas, temporales y de uso del suelo, y validar el empleo de sensores de bajo costo para determinar partículas finas en áreas urbanas.

### Objetivos específicos

  1. Describir la variación espacio temporal de la concentración de aerosoles colectados con sensores de bajo costo en zonas del Área Metropolitana de Córdoba, Argentina.

  * Conclusiones capítulo [2](#cap:sens) y [3](#cap:expl): La implementación de sistemas de monitoreo de bajo costo demostró ser efectiva y funcional, proporcionando datos consistentes con las mediciones de estaciones de referencia. Se observó que la concentración de PM~2.5~ en Córdoba fue menor que en otras ciudades del mundo, aunque se superaron los estándares locales en varias ocasiones. Las características temporales y espaciales de la concentración de PM~2.5~ permitieron explicar la variabilidad observada, con diferencias significativas en función del uso del suelo (industrial, urbano y agrícola/área verde).

  2. Evaluar la utilidad de sensores de bajo costo para el estudio de aerosoles en zonas urbanas del Área Metropolitana de Córdoba, Argentina. 
  
  * Conclusiones capítulo [2](#cap:sens): Los sensores de bajo costo mostraron una alta consistencia en sus mediciones y una correlación significativa con las estaciones de referencia, validando su utilidad para el monitoreo de la calidad del aire en áreas urbanas de Córdoba. Estos sistemas representan una alternativa viable y económica para la gestión y control de la calidad del aire.
  
  3. Analizar la influencia de distintos tipos de variables obtenidas a través de satélites, entre ellas meteorológicas, en los patrones de variación temporal de aerosoles en el Área Metropolitana de Córdoba, Argentina.
  
  * Conclusiones capítulo [4](#cap:var): Las variables meteorológicas y derivadas de información satelital demostraron tener un impacto sustancial en la concentración de PM~2.5~. Estas variables, integradas en un sistema dinámico e interdependiente, explican la variabilidad espacio-temporal de la concentración de PM~2.5~ y son fundamentales para el desarrollo de modelos predictivos precisos.
  
  4. Validar el empleo de productos satelitales, tales como AOD (del inglés *Aerosol Optical Depth*), para estimar la concentración de material particulado en el Área Metropolitana de Córdoba, Argentina, a través de análisis estadísticos. 
  
  * Conclusiones capítulo [4](#cap:var): El análisis de la covariación entre variables satelitales y la concentración de PM~2.5~ confirmó la validez de estos productos para estimar la concentración de material particulado. Este análisis justificó su inclusión en la base de datos para el desarrollo de modelos predictivos.
  
  5. Proponer un modelo predictivo que incluya variables de uso del suelo, satelitales y temporales para la estimación de la concentración de aerosoles en el Área Metropolitana de Córdoba, Argentina.
  
  * Conclusiones capítulo [5](#cap:mod): Los modelos predictivos desarrollados lograron explicar la variabilidad de la concentración de PM~2.5~ utilizando variables satelitales y temporales. Los modelos demostraron una capacidad adecuada para alertar a la población con anticipación sobre condiciones adversas de calidad del aire, con una precisión variable según el tipo de uso del suelo y el algoritmo empleado.

### Conclusión Final

  La presente tesis ha demostrado que los sensores de bajo costo son herramientas eficaces para monitorear la concentración de PM~2.5~ en áreas urbanas. La integración de variables satelitales y meteorológicas ha permitido desarrollar modelos predictivos precisos, capaces de alertar a la población sobre condiciones adversas de calidad del aire con suficiente antelación. Los resultados obtenidos no solo validan el empleo de sensores de bajo costo, sino que también destacan la importancia de considerar la variabilidad espacio-temporal y las características del uso del suelo al desarrollar estrategias de gestión de la calidad del aire. La tesis cumple con el objetivo general y los objetivos específicos planteados, aportando soluciones prácticas y conocimiento científico relevante para el monitoreo y la gestión de la calidad del aire en la provincia de Córdoba. 

# Futuras lineas de investigación {-}

  Se propone como futuro lineamiento de continuación de esta tesis el estudio de la variabilidad conjunta de la concentración de PM~2.5~ con respecto a cada una de las variables derivadas a partir de información satelital con el objetivo de identificar cuáles son las que más covarían con la concentración de este contaminante. Sería interesante considerar también las correlaciones entre las potenciales variables explicativas para caracterizar el sistema de correlaciones y dependencias, como se hace en un análisis de sendero o modelo de ecuaciones estructurales. 
  
  También se promueve hacer hincapié en la comparación del desempeño de los modelos predictivos de concentración de PM~2.5~ implementados en esta tesis con otros algoritmos predictivos entrenados en el contexto de aprendizaje automático que aprovechen datos de imágenes satelitales o bien la combinación de datos satelitales y meteorológicos tabulares con imágenes.
  
  Además, se podría implementar un procedimiento de simulación para verificar los resultados obtenidos en la presente tesis. Este tendría por objetivo simular series con distinto grado de variabilidad (alto y bajo), además de múltiples variables predictoras. Una vez llevada a cabo la simulación proceder al ajuste de los modelos predictivos evaluados en la presente tesis, para confirmar las conclusiones obtenidas a partir de los datos observados desde las obtenidas con los datos simulados. Una conclusión de la presente tesis a confirmar es la que establece que el modelado predictivo de series temporales con características de gran variabilidad y fluctuaciones entre sus valores es mejor de ser realizado a través de redes neuronales recurrentes; Mientras que el modelado predictivo de series temporales de baja variabilidad y fluctuaciones es mejor bajo el algoritmo de bosques aleatorios. 
  
  Además, se podría implementar un procedimiento de simulación para verificar los resultados obtenidos en la presente tesis. Este tendría por objetivo simular series temporales con distintos grados de variabilidad (alto y bajo) y múltiples variables predictoras. La simulación consistiría en generar datos sintéticos que imiten las características de las series temporales observadas, permitiendo un control más riguroso sobre su variabilidad y las relaciones entre variables. Una vez llevada a cabo la simulación, se procedería al ajuste de los modelos predictivos similares a los evaluados en la presente tesis, como las redes neuronales recurrentes (*RNN*) y los bosques aleatorios (*Random Forest*), utilizando estos datos simulados. Esto permitiría confirmar si las conclusiones obtenidas a partir de los datos observados se mantienen con los datos simulados. La conclusión de la presente tesis a confirmar es la que establece que el modelado predictivo de series temporales con características de gran variabilidad y fluctuaciones considerables entre sus valores es mejor realizado a través de redes neuronales recurrentes. Estas redes son capaces de capturar dependencias temporales complejas y no lineales. Mientras que el modelado predictivo de series temporales de baja variabilidad y fluctuaciones más estables es mejor bajo el algoritmo de bosques aleatorios, que es robusto y eficaz para captar relaciones en datos con menor ruido y variabilidad. La simulación ayudaría a validar estas conclusiones al proporcionar un entorno controlado en el que se pueda evaluar el rendimiento de cada modelo bajo diferentes condiciones de variabilidad.
  
  Finalmente, se propone la implementación del modelo predictivo en producción, este inciso persigue el objetivo de poner en funcionamiento el modelo desarrollado, permitiendo la consulta de datos por medio de la población.